### ISSUE TITLE
Storj is no more available on "ROI" tab

### ISSUE THREAD

**Issue by jeremyfritzen** [ZumZoom/analytics#12]
Hi,

I've been using this application for 2 months but it seems that, recently, STORJ is no more available on it.

![image](https://user-images.githubusercontent.com/26802442/90483975-df0e6400-e135-11ea-8dfc-61d16f5bc314.png)

Is that normal?
If so, why did you choose to de-reference it?

Thank you!

**Comment by ZumZoom** [comment]
It is normal because STORJ pool became illiquid: https://v1.uniswap.info/token/0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac
I guess most of the LPs migrated to Uniswap V2 already.

**Comment by jeremyfritzen** [comment]
Thanks!
I thought ZumZoom was designed also for Uniswap V2. Is it planned to include V2 pools?

**Comment by ZumZoom** [comment]
It is not planned yet but it will probably happen sooner or later :)
