### ISSUE TITLE
Bancor COT/BNT data missing after Nov 9

### ISSUE THREAD

**Issue by adaptivedev** [ZumZoom/analytics#13]
Can this be because the converter was updated from v2 to v2.1 around that time? 

https://zumzoom.github.io/analytics/bancor/roi/

![image](https://user-images.githubusercontent.com/3179917/99756673-86d35f00-2aa2-11eb-912e-e18cfb1bb568.png)

**Comment by ZumZoom** [comment]
Probably. But now it shows the data for the latest converter.
